### ISSUE TITLE
安全漏洞提醒

### ISSUE THREAD

**Issue by code6er** [go-programming-tour-book/blog-service#1]
漏洞类型：邮箱 SMTP 信息泄露

漏洞等级：高

漏洞地址：https://github.com/go-programming-tour-book/blog-service/blob/2b844e26ab03da122facb7a35d328f545fa1c9f6/configs/config.yaml

漏洞危害：任何人可以通过 SMTP 账号密码收发邮件，进而通过邮箱重置其他平台密码

解决方案：重置 SMTP 密码并检查邮箱是否有敏感信息泄露（请勿只修改代码，历史版本库依旧可见）

本次扫描结果由 [ 码小六 ] https://github.com/4x99/code6 提供（欢迎 star）

**Comment by eddycjy** [comment]
已修复，已关闭 SMTP 服务，感谢反馈。
