### ISSUE TITLE
router.go的鉴权使用方法错误

### ISSUE THREAD

**Issue by luhaopei** [go-programming-tour-book/blog-service#14]
r.POST("/auth", api.GetAuth)改为r.GET("/auth", api.GetAuth)

**Comment by LaChimere** [comment]
> r.POST("/auth", api.GetAuth)改为r.GET("/auth", api.GetAuth)

我写成 `r.POST("/auth", api.GetAuth)` 的时候，验证接口的得到了如下结果：
```
{"code":10000001,"details":["AppKey为必填字段","AppSecret为必填字段"],"msg":"passed-in parameter error"}
```

换成 `r.GET("/auth", api.GetAuth)`，验证时是：
```
404 page not found
```

**Comment by SashiRin** [comment]
@LaChimere 书里说的是AppKey和AppSecret常放在Header里传送的话，app.BindAndValid就应该加个是否bind header的判断，因为里面的c.ShouldBind是bind request body里面的参数。如果要bind request header里面的参数的话应该用c.ShouldBindHeader.

**Comment by minibear2333** [comment]
可以参考我写的代码，已经对此做了修复，识别header解析的正确方法
https://github.com/golang-minibear2333/gin-blog/commit/83236bc06a13d3968f36b2c305f4f5f759f4b27b

**Comment by minibear2333** [comment]
@eddycjy 

> 可以参考我写的代码，已经对此做了修复，识别header解析的正确方法
> [golang-minibear2333/gin-blog@83236bc](https://github.com/golang-minibear2333/gin-blog/commit/83236bc06a13d3968f36b2c305f4f5f759f4b27b)
